#! /bin/bash

rm -rf temp

mkdir temp

cp -r core-class/* temp

cp app/build/intermediates/classes/debug/org/jivesoftware/smack/Packet/Stanza.class temp/org/jivesoftware/smack/packet/

cp app/build/intermediates/classes/debug/org/jivesoftware/smack/Packet/Message*.class temp/org/jivesoftware/smack/packet/

cp app/build/intermediates/classes/debug/org/jivesoftware/smack/util/PacketParserUtils*.class temp/org/jivesoftware/smack/util/

cp app/build/intermediates/classes/debug/org/jivesoftware/smack/filter/MessageTypeFilter.class temp/org/jivesoftware/smack/filter/

cd temp

jar -cf smack-core-4.1.1.jar *

mv smack-core-4.1.1.jar ../

cd ..

rm -rf temp

echo "Done"
